spring:
  application:
    name: storeApp

  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: dev
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600 # 10 minutes
    refreshTokenExpiration: 604800 # 7 days

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
