spring:
  application:
    name: storeApp
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: root
    password: projit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 minutes
    refreshTokenExpiration: 604800 # 7 days