spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: root
    password: projit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

websiteUrl: http://localhost:8080